# name= input("Enter your name: ")
# print("welcome:",name)
# age= input("Enter your age: ")
# print("your age:",age)

# val=input("enter some value:")
# print(type(val),val)
int("7")
val=int(input("enter some value:"))
print(type(val),val)

int("7")
val=float(input("enter some value:"))
print(type(val),val)

name=input("enter name:")
age=input("enter your age:")
marks=float(input("enter your marks:"))
print("welcome",name)
print("age:",age)
print("marks=",marks)